### ISSUE TITLE
Feature suggestion : to be able to reinstall on a previous installation  without erasing the home.

### ISSUE THREAD

**Issue by grimlokason** [zweiler2/HoloISO_Nvidia#24]
Hello,

In the part ```echo "Choose your partitioning type:"```  it would be great to be able to use the previous created partition and just format the efi and root.

for a 1st test, if ok , i can try to provide a PR with a third choice in wich we can choose which partition is the EFI, which is the root and which is the home. 
it'll skip the partition creation and is just going to format the efi and root.

Best regards.

**Comment by zweiler2** [comment]
Thank you for this feature request and offering a PR.
You can already reuse the home partition, if you select "Use entire drive". But since you wrote this, i think i should make it clearer to see that this is possible.

By you writing this, you've made me aware of a bug with it. Similar to #23. So thank you for that.
Since you were offering a PR i assume you know your "bash fu" and "git diff" perhaps aswell; I know this isn't quite the same thing you were suggesting, but please have a look at it and tell me what you think.
[install_holoiso.txt](https://github.com/zweiler2/HoloISO_Tweaked/files/14221684/install_holoiso.txt) (Rename to .sh, GH doesn't allow .sh uploads)

And if you think a 3rd option would be nice/needed aswell, then please feel free to make a PR; i'd appreciate it :)
Thanks

**Comment by zweiler2** [comment]
Closing due to no response and also the feature is implemented with [this](https://github.com/zweiler2/HoloISO_Tweaked/commit/ab105faef72c4932883569a2caf88cb99749a758) commit.
